spring:
  application:
    name: registry-service
  cloud:
    service-registry:
      auto-registration:
        enabled: false   # <-- DESACTIVA el eurekaAutoServiceRegistration

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
